# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 19:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20170508_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sentence_pairs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[['', '']]),
            preserve_default=False,
        ),
    ]
