# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 19:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_project_sentence_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sentence_pairs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[['', '']]),
        ),
    ]
