# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20170513_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mappings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[[[[[0, 0], [0, 0]], [[0, 0]]]]]),
        ),
        migrations.AddField(
            model_name='project',
            name='tokens',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
