# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20170514_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='projects_id',
        ),
    ]
