# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20170514_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inputText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='outputText',
            field=models.TextField(default=''),
        ),
    ]
